-- Phase 1: Voice AI & 2-Way SMS Engine Schema Migration
-- Run this entire block in the Supabase SQL Editor (https://supabase.com/dashboard -> SQL Editor -> New Query)

-- 1. Calls table: stores Twilio call records and transcripts
CREATE TABLE IF NOT EXISTS calls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    call_sid TEXT UNIQUE,
    from_number TEXT NOT NULL,
    to_number TEXT NOT NULL,
    duration INTEGER DEFAULT 0,
    transcript TEXT,
    recording_url TEXT,
    status TEXT DEFAULT 'completed',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Messages table: stores threaded 2-way SMS conversations
CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id BIGINT REFERENCES leads(id) ON DELETE CASCADE,
    from_number TEXT NOT NULL,
    to_number TEXT NOT NULL,
    direction TEXT CHECK (direction IN ('inbound', 'outbound')),
    body TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Extend leads table with address, preferred window, call reference
ALTER TABLE leads ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS preferred_window TEXT DEFAULT 'Flexible';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS call_sid TEXT;

-- 4. RLS for calls
ALTER TABLE calls ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all access to calls" ON calls;
CREATE POLICY "Allow all access to calls" ON calls FOR ALL USING (true) WITH CHECK (true);

-- 5. RLS for messages
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all access to messages" ON messages;
CREATE POLICY "Allow all access to messages" ON messages FOR ALL USING (true) WITH CHECK (true);
